Use this utlity to update the returns and std_dev fields within investment-options.csv

In [1]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

%matplotlib inline

In [3]:
# Set size of inline plots.
'''note: rcParams can't be in same cell as import matplotlib
   or %matplotlib inline
   
   %matplotlib notebook: will lead to interactive plots embedded within
   the notebook, you can zoom and resize the figure
   
   %matplotlib inline: only draw static images in the notebook
'''
plt.rcParams["figure.figsize"] = (10, 7)

Globals

In [4]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = True

In [5]:
# Read in nasdaq100.csv
nasdaq100 = pd.read_csv('nasdaq100.csv')
#nasdaq100.drop(columns=['SEC filings'], inplace=True)
nasdaq100.rename(columns={'Ticker': 'Symbol',
                      'Company':'Description'}, inplace=True)
nasdaq100.set_index("Symbol", inplace=True)
nasdaq100

,Description,GICS Sector,GICS Sub-Industry
Symbol,,,
ADBE,Adobe Inc.,Information Technology,Application Software
AMD,Advanced Micro Devices,Information Technology,Semiconductors
ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines"
GOOGL,Alphabet Inc. (Class A),Communication Services,Interactive Media & Services
GOOG,Alphabet Inc. (Class C),Communication Services,Interactive Media & Services
...,...,...,...
VRTX,Vertex Pharmaceuticals,Health Care,Biotechnology
WBD,Warner Bros. Discovery,Communication Services,Broadcasting
WDAY,"Workday, Inc.",Information Technology,Application Software
XEL,Xcel Energy,Utilities,Multi-Utilities
ZS,Zscaler,Information Technology,Application Software

In [6]:
# Read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Energy': 'US Stocks:Energy',
 'Materials': 'US Stocks:Materials',
 'Industrials': 'US Stocks:Industrials',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Health Care': 'US Stocks:Healthcare',
 'Financials': 'US Stocks:Financials',
 'Information Technology': 'US Stocks:Technology',
 'Communication Services': 'US Stocks:Communication Services',
 'Utilities': 'US Stocks:Utilities',
 'Real Estate': 'US Stocks:Real Estate'}

In [7]:
# Add Asset Class column.
nasdaq100['Asset Class'] = 'US Stocks'

# Yahoo finance uses '-' where '.' is used in symbol names.
nasdaq100.index = nasdaq100.index.str.replace('.', '-', regex=False)
nasdaq100

,Description,GICS Sector,GICS Sub-Industry,Asset Class
Symbol,,,,
ADBE,Adobe Inc.,Information Technology,Application Software,US Stocks
AMD,Advanced Micro Devices,Information Technology,Semiconductors,US Stocks
ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines",US Stocks
GOOGL,Alphabet Inc. (Class A),Communication Services,Interactive Media & Services,US Stocks
GOOG,Alphabet Inc. (Class C),Communication Services,Interactive Media & Services,US Stocks
...,...,...,...,...
VRTX,Vertex Pharmaceuticals,Health Care,Biotechnology,US Stocks
WBD,Warner Bros. Discovery,Communication Services,Broadcasting,US Stocks
WDAY,"Workday, Inc.",Information Technology,Application Software,US Stocks
XEL,Xcel Energy,Utilities,Multi-Utilities,US Stocks
ZS,Zscaler,Information Technology,Application Software,US Stocks

In [8]:
# Make symbols list.
symbols = list(nasdaq100.index)
#symbols

In [9]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries)
bb.compile_timeseries(symbols)

ADBE AMD ABNB GOOGL GOOG AMZN AEP AMGN ADI ANSS AAPL AMAT APP ARM ASML AZN TEAM ADSK ADP AXON BKR BIIB BKNG AVGO CDNS CDW CHTR CTAS CSCO CCEP CTSH CMCSA CEG CPRT CSGP COST CRWD CSX DDOG DXCM FANG DASH EA EXC FAST FTNT GEHC GILD GFS HON IDXX INTC INTU ISRG KDP KLAC KHC LRCX LIN LULU MAR MRVL MELI META MCHP MU MSFT MSTR MDLZ MDB MNST NFLX NVDA NXPI ORLY ODFL ON PCAR PLTR PANW PAYX PYPL PDD PEP QCOM REGN ROP ROST SBUX SNPS TTWO TMUS TSLA TXN TTD VRSK VRTX WBD WDAY XEL
Throttle limit reached. Waiting for 30 seconds...
ZS

In [10]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df = df[:]
df

,ADBE,AMD,ABNB,GOOGL,GOOG,AMZN,AEP,AMGN,ADI,ANSS,...,TMUS,TSLA,TXN,TTD,VRSK,VRTX,WBD,WDAY,XEL,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,224.57,18.83,NaN,52.54,52.11,76.96,58.42,158.59,76.83,143.01,...,63.82,20.67,79.35,11.62,104.55,164.08,25.83,159.74,40.30,39.81
2019-01-03,215.70,17.05,NaN,51.09,50.62,75.01,58.28,156.17,72.19,137.64,...,63.58,20.02,74.67,10.96,101.35,163.73,25.68,154.02,40.14,39.32
2019-01-04,226.19,19.00,NaN,53.71,53.34,78.77,58.82,161.51,73.95,143.66,...,66.00,21.18,78.05,11.79,105.83,172.70,26.14,163.35,40.54,41.77
2019-01-07,229.26,20.57,NaN,53.60,53.23,81.48,58.49,163.69,74.41,147.32,...,66.93,22.33,79.40,12.46,105.93,175.85,26.53,163.50,40.36,43.56
2019-01-08,232.68,20.75,NaN,54.07,53.62,82.83,59.21,165.78,76.23,148.05,...,66.27,22.36,79.30,12.81,106.88,178.19,27.24,166.95,40.83,43.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-24,444.42,108.11,144.82,179.25,181.19,212.71,106.29,309.72,236.99,333.63,...,267.24,330.53,200.74,74.20,297.01,481.65,11.09,261.81,70.78,197.05
2025-02-25,443.41,103.96,141.55,175.42,177.37,212.80,107.64,315.63,235.30,330.40,...,269.64,302.80,199.98,74.98,299.72,480.35,10.69,255.22,70.45,193.04
2025-02-26,441.50,104.74,144.03,172.73,174.70,214.35,106.89,306.38,233.73,332.32,...,262.70,290.80,198.24,72.43,288.03,479.10,10.50,271.09,69.97,195.82
2025-02-27,437.19,99.51,139.45,168.50,170.21,208.74,105.16,305.82,223.85,330.37,...,263.29,281.95,191.30,71.49,290.11,474.50,11.00,260.57,70.76,192.03
2025-02-28,438.56,99.86,138.87,170.28,172.22,212.28,106.05,308.06,230.06,333.25,...,269.69,292.98,195.99,70.32,296.91,479.79,11.46,263.34,72.10,196.23

In [11]:
# Sample symbol.
symbol = 'AMZN'

In [12]:
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns[symbol]

np.float64(22.323387686946326)

In [13]:
# Calculate 1 month, 3 months, 1 year, 3 year, and 5 year annualized returns.
annual_returns_1mo = bb.annualized_returns(df, timeperiod='daily', years=1/12)
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [14]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change()
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)
vola[symbol]

np.float64(0.2658277126401949)

In [15]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)
ds_vola[symbol]

np.float64(0.19211925893150925)

In [16]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [17]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change()
monthly_returns[symbol]

Date
2019-01-31     NaN
2019-02-28   -0.05
2019-03-31    0.09
2019-04-30    0.08
2019-05-31   -0.08
              ...
2024-10-31    0.00
2024-11-30    0.12
2024-12-31    0.06
2025-01-31    0.08
2025-02-28   -0.11
Freq: ME, Name: AMZN, Length: 74, dtype: float64

In [18]:
# Calculate 3 year annualized standard deviation.
std_dev = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev[symbol]

np.float64(0.3524324120095102)

In [19]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]
lines

['# Description: S&P 400 investment options. 10/02/2020',
 '',
 '# Format',
 '"Investment Option","Description","Asset Class","1 mo","3 mo","1 Yr","3 Yr","5 Yr","Vola","DS Vola","Std Dev"',
 '# Note: "Description" field is optional']

In [20]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

# This is still slow (2.53 s).
for i, (index, row) in enumerate(nasdaq100.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_1mo = annual_returns_1mo[symbol]
    ret_3mo = annual_returns_3mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd = std_dev[symbol]*100
    
    out.append(
        '"{}","{}","{}","{:0.2f}","{:0.2f}","{:0.2f}","{:0.2f}","{:0.2f}","{:0.2f}","{:0.2f}","{:0.2f}"'
        .format(symbol, description, asset_class,
                ret_1mo, ret_3mo, ret_1yr, ret_3yr, ret_5yr, _vola, _ds_vola, sd))

In [21]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')